"""empty message

Revision ID: 58677ea5338a
Revises: 92c98b8223bd
Create Date: 2020-05-05 15:27:55.896044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58677ea5338a'
down_revision = '92c98b8223bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pic', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic')
    # ### end Alembic commands ###
