"""empty message

Revision ID: 92c98b8223bd
Revises: a62766bc7a01
Create Date: 2020-04-28 11:44:31.650450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92c98b8223bd'
down_revision = 'a62766bc7a01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_locations', sa.Column('state', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_locations', 'state')
    # ### end Alembic commands ###
