"""empty message

Revision ID: a62766bc7a01
Revises: 6ade7f1e46f9
Create Date: 2020-04-27 15:16:47.838303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a62766bc7a01'
down_revision = '6ade7f1e46f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_locations', sa.Column('zipcode', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_locations', 'zipcode')
    # ### end Alembic commands ###
